imports:
    - { resource: config.yml }

debug:
    level: error #Monolog supports all 8 logging levels defined in RFC 5424, but unless you specifically need syslog compatibility, it is advised to only use DEBUG, INFO, WARNING, ERROR, CRITICAL, ALERT.
    toolbar: false
    handlers: [ files ] # possible handlers: files, chrome, firebug