homepage:
    pattern: /

admin:
    pattern: /admin
    defaults: { module: admin }

admin2:
    pattern: /admin/{act}
    defaults: { module: admin }

doc:
    pattern: /{document_srl}
    requirements:
        document_srl: '\d+'
doc_slash:
    pattern: /{document_srl}/
    requirements:
        document_srl: '\d+'

mid:
    pattern: /{mid}
    requirements:
        mid: '[a-zA-Z0-9_]+'

mid_slash:
    pattern: /{mid}/
    requirements:
        mid: '[a-zA-Z0-9_]+'

page:
    pattern: /show/{mid}
    requirements:
        mid: '[a-zA-Z0-9_]+'
    defaults:
        _controller: pageView::dispPageIndex

mid_doc:
    pattern: /{mid}/{document_srl}
    requirements:
        mid: '[a-zA-Z0-9_]+'
        document_srl: '\d+'

vid_mid:
    pattern: /{vid}/{mid}
    requirements:
        vid: '[a-zA-Z0-9_]+'
        mid: '[a-zA-Z0-9_]+'

vid_mid_doc:
    pattern: /{vid}/{mid}/{document_srl}
    requirements:
        vid: '[a-zA-Z0-9_]+'
        mid: '[a-zA-Z0-9_]+'
        document_srl: '\d+'

mid_entry:
    pattern: /{mid}/entry/{entry}
    requirements:
        mid: '[a-zA-Z0-9_]+'

vid_mid_entry:
    pattern: /{vid}/{mid}/entry/{entry}
    requirements:
        vid: '[a-zA-Z0-9_]+'
        mid: '[a-zA-Z0-9_]+'

shop_product:
    pattern: /{vid}/{type}/{identifier}
    defaults:
        _controller: shopView::route
