admin:
    pattern: /admin
    defaults: { module: admin }

doc:
    pattern: /{document_srl}
    requirements:
        document_srl: \d+

mid:
    pattern: /{mid}
    requirements:
        mid: '[a-zA-Z0-9_]+'

mid_doc:
    pattern: /{mid}/{document_srl}
    requirements:
        mid: '[a-zA-Z0-9_]+'
        document_srl: '\d+'

vid_mid:
    pattern: /{vid}/{mid}
    requirements:
        vid: '[a-zA-Z0-9_]+'
        mid: '[a-zA-Z0-9_]+'

vid_mid_doc:
    pattern: /{vid}/{mid}/{document_srl}
    requirements:
        vid: '[a-zA-Z0-9_]+'
        mid: '[a-zA-Z0-9_]+'
        document_srl: '\d+'

mid_entry:
    pattern: /{mid}/entry/{entry}
    requirements:
        mid: '[a-zA-Z0-9_]+'

vid_mid_entry:
    pattern: /{vid}/{mid}/entry/{entry}
    requirements:
        vid: '[a-zA-Z0-9_]+'
        mid: '[a-zA-Z0-9_]+'

