parameters:
    logger.debug.level: debug
    logger.debug.toolbar: true;
    logger.slow_queries_threshold: 800

services:
    logger_handler_template:
        abstract: true
        class: 'Monolog\Handler\StreamHandler'

    # dev.requests.log
    logger.handler.stream.requests:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/%kernel.environment%.requests.log', '%logger.debug.level%' ]
    # dev.errors.log
    logger.handler.stream.errors:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/%kernel.environment%.errors.log', '%logger.debug.level%' ]
    # dev.php_errors.log
    logger.handler.stream.php_errors:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/%kernel.environment%.php_errors.log', '%logger.debug.level%' ]
    # dev.queries.log
    logger.handler.stream.db_info:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/%kernel.environment%.queries.log', '%logger.debug.level%' ]
    # dev.slow_queries.log
    logger.handler.stream.db_slow_query:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/%kernel.environment%.slow_queries.log', '%logger.debug.level%' ]

    logger_template:
        abstract: true
        class: 'Monolog\Logger'


    logger.db_errors:
        parent: logger_template
        arguments: [ 'db' ]
        calls:
            - [pushHandler, [@logger.handler.stream.errors]]
    logger.exceptions:
        parent: logger_template
        arguments: [ 'cms' ]
        calls: [ [pushHandler, [@logger.handler.stream.errors]] ]


    logger.requests:
        parent: logger_template
        arguments: [ 'cms' ]
        calls: [ [pushHandler, [@logger.handler.stream.requests]] ]
    logger.db_info:
        parent: logger_template
        arguments: [ 'db' ]
        calls: [ [pushHandler, [@logger.handler.stream.db_info]] ]
    logger.db_slow_query:
        parent: logger_template
        arguments: [ 'db' ]
        calls: [ [pushHandler, [@logger.handler.stream.db_slow_query]] ]
    logger.php_errors:
        parent: logger_template
        arguments: [ 'cms' ]
        calls: [ [pushHandler, [@logger.handler.stream.php_errors]] ]


    listener.db.errors:
        class: 'Karybu\Module\Debug\EventListener\QueryErrorListener'
        arguments: [ @logger.db_errors ]
        tags:
            - { name: cms.event_listener }
    listener.exception:
        class: 'Karybu\EventListener\ExceptionListener'
        arguments: [ @logger.exceptions ]
        tags:
            - { name: cms.event_listener }
