parameters:
    logger.debug.level: debug
    logger.debug.toolbar: true;
    logger.slow_queries_threshold: 800

services:
    logger_handler_template:
        abstract: true
        class: 'Monolog\Handler\StreamHandler'

    # TODO Enable and disable logging based on the parameters above - maybe load a different container?
    logger.handler.stream:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/%kernel.environment%.log', '%logger.debug.level%' ]
    logger.handler.stream.errors:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/errors_%kernel.environment%.log', '%logger.debug.level%' ]
    logger.handler.stream.db_info:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/db_info_%kernel.environment%.log', '%logger.debug.level%' ]
    logger.handler.stream.db_slow_query:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/db_slow_query_%kernel.environment%.log', '%logger.debug.level%' ]
    logger.handler.stream.db_errors:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/db_errors_%kernel.environment%.log', '%logger.debug.level%' ]

    logger_template:
        abstract: true
        class: 'Monolog\Logger'

    logger:
        parent: logger_template
        arguments: [ 'cms' ]
        calls: [ [pushHandler, [@logger.handler.stream]] ]
    logger.exceptions:
        parent: logger_template
        arguments: [ 'cms' ]
        calls: [ [pushHandler, [@logger.handler.stream.errors]] ]
    logger.db_info:
        parent: logger_template
        arguments: [ 'db' ]
        calls: [ [pushHandler, [@logger.handler.stream.db_info]] ]
    logger.db_slow_query:
        parent: logger_template
        arguments: [ 'db' ]
        calls: [ [pushHandler, [@logger.handler.stream.db_slow_query]] ]
    logger.db_errors:
        parent: logger_template
        arguments: [ 'db' ]
        calls:
            - [pushHandler, [@logger.handler.stream.db_errors]]
            - [pushHandler, [@logger.handler.stream.errors]]


    listener.db.errors: { class: 'Karybu\Module\Debug\EventListener\QueryErrorListener', arguments: [ @logger.db_errors ] }
    listener.error.handler: { class: 'Karybu\EventListener\ErrorHandler' }


