parameters:
    logger.debug: <?php echo Monolog\Logger::DEBUG ?>
    log_slow_query: __LOG_SLOW_QUERY__
    log_slow_query_min_duration: __LOG_SLOW_QUERY__
    log_query_errors: __DEBUG_DB_OUTPUT__
    show_request_response_info: <?php echo (__DEBUG__ & 2 ? 'true' : 'false') . "\n" ?>
    show_db_queries_info: <?php echo (__DEBUG__ & 4 ? 'true' : 'false') . "\n" ?>
    log_info_in_firebug_console: <?php echo (__DEBUG_OUTPUT__ == 2 ? 'true' : 'false') . "\n" ?>

services:
    logger_handler_template:
        abstract: true
        class: 'Monolog\Handler\StreamHandler'

    # TODO Enable and disable logging based on the parameters above - maybe load a different container?
    logger.handler:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/%kernel.environment%.log', '%logger.debug%' ]
    logger.errors:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/errors_%kernel.environment%.log', '%logger.debug%' ]
    logger.handler.db_info:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/db_info_%kernel.environment%.log', '%logger.debug%' ]
    logger.handler.db_slow_query:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/db_slow_query_%kernel.environment%.log', '%logger.debug%' ]
    logger.handler.db_errors:
        parent: logger_handler_template
        arguments: [ '%kernel.logs_dir%/db_errors_%kernel.environment%.log', '%logger.debug%' ]

    logger_template:
        abstract: true
        class: 'Monolog\Logger'

    logger:
        parent: logger_template
        arguments: [ 'cms' ]
        calls: [ [pushHandler, [@logger.handler]] ]
    logger.exceptions:
        parent: logger_template
        arguments: [ 'cms' ]
        calls: [ [pushHandler, [@logger.errors]] ]
    logger.db_info:
        parent: logger_template
        arguments: [ 'db' ]
        calls: [ [pushHandler, [@logger.handler.db_info]] ]
    logger.db_slow_query:
        parent: logger_template
        arguments: [ 'db' ]
        calls: [ [pushHandler, [@logger.handler.db_slow_query]] ]
    logger.db_errors:
        parent: logger_template
        arguments: [ 'db' ]
        calls:
            - [pushHandler, [@logger.handler.db_errors]]
            - [pushHandler, [@logger.errors]]

    listener.db.query_info: { class: 'Karybu\Module\Debug\EventListener\DBQueryInfoListener', arguments: [ @logger.db_info ] }
    listener.db.slow_query: { class: 'Karybu\Module\Debug\EventListener\SlowQueryListener', arguments: [ '%log_slow_query_min_duration%', @logger.db_slow_query ] }
    listener.db.errors: { class: 'Karybu\Module\Debug\EventListener\QueryErrorListener', arguments: [ @logger.db_errors ] }
    listener.error.handler: { class: 'Karybu\EventListener\ErrorHandler' }
    listener.response.summary: { class: 'Karybu\Module\Debug\EventListener\ResponseSummaryInfoListener', arguments: [@logger] }

    listener.debug.toolbar:
        class: 'Karybu\Module\Debug\EventListener\DebugToolbarListener'
        arguments: [ @cms.context.instance, '%kernel.debug%' ]
        calls:
            - [enableQueriesInfo, [@listener.db.query_info]]
            - [enableFailedQueriesInfo, [@listener.db.errors]]
            - [enablePHPErrorsInfo, [@listener.error.handler]]
